POST {{baseDeployUrl}}/deploy
Content-Type: application/json

{
  "ProtocolId": "test",
  "ProtocolType": "HTTP_SERVER",
  "DeviceInfoMap": {
    "testDeviceGroupId": [
      {
        "DeviceId": "testDeviceId",
        "DeviceName": "testDeviceName"
      }
    ]
  },
  "Number": 2
}

###
POST {{baseDeployUrl}}/deploy
Content-Type: application/json

{
  "ProtocolId": "test2",
  "ProtocolType": "TCP_SERVER",
  "DeviceInfoMap": {
    "testDeviceGroupId2365": [
      {
        "DeviceId": "testDeviceId2",
        "DeviceName": "testDeviceName"
      }
    ]
  },
  "Properties": {
    "port": 12349
  },
  "Number": 2
}

###
GET {{baseDeployUrl}}/protocolAll
Content-Type: application/json

###
POST {{baseUrl}}:8787/testDeviceGroupId/testDeviceId/propertyReport
Content-Type: application/json

{
  "a": "b"
}